# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, ’10.0’

use_frameworks!

target 'EuroLeagueKit' do
    pod 'Alamofire', '~> 4.4'
    pod 'RealmSwift'
    pod 'SWXMLHash', '~> 4.0.0'
end
