# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, ’10.0’


  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!

def app_pods
    pod 'EuroLeagueKit', :path => './EuroLeagueKit'
end

def app_ui_pods
    pod 'SDWebImage', '~>3.8'
    pod 'XLPagerTabStrip', '~> 7.0'
    pod 'AKSideMenu'
end

target 'Euroleague-Graduate' do
    app_ui_pods
    app_pods
end

target 'Euroleague-GraduateTests' do
    app_pods
end
